<?php
$z[0]=Array("global","",921,948);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1037,1064);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1067,1093);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n            <li class=\"mainnav_line\"></li>\r\n            <li><a href=\"[field:typeurl/]\" title=\"\">[field:typename/]</a></li>\r\n            ",1699,1885);
$z[3][4]['type']="top";
$z[3][4]['row']="9";
$z[4]=Array("arclist"," <a href=\"[field:arcurl]\" title=\"[field:title/]\" class=\"zh1 displayb fl\">[field:title/]&nbsp;&nbsp;[field:stime/]</a>",2085,2313);
$z[4][4]['typeid']="38";
$z[4][4]['row']="5";
$z[4][4]['titlelen']="50";
$z[4][4]['infolen']="";
$z[4][4]['imgwidth']="100";
$z[4][4]['imgheight']="80";
$z[5]=Array("global","",2445,2470);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",2848,2880);
$z[6][4]['name']="cfg_templets_skin";

?>