<?php
$z[0]=Array("field","",255,278);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",279,305);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",327,359);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",424,456);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",522,554);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",617,649);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",740,775);
$z[6][4]['filename']="head.htm";
$z[7]=Array("list","\r\n					 <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><span class=\"tit\">[[field:typename/]]</span>[field:title/]&nbsp;&nbsp;<b style=\"color:#ff0000;\">[field:flag/]</b></a><span class=\"time\">[field:stime/]</span></li>\r\n					 ",1660,2002);
$z[7][4]['col']="1";
$z[7][4]['titlelen']="90";
$z[7][4]['nfolen']="100";
$z[7][4]['imgwidth']="60";
$z[7][4]['imgheight']="40";
$z[7][4]['pagesize']="30";
$z[7][4]['typeid']="";
$z[8]=Array("pagelist","",2122,2195);
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index pre pageno next end option";
$z[9]=Array("include","",2386,2423);
$z[9][4]['filename']="footer.htm";

?>